"""JUnit XML parser for external test result import.

Parses JUnit-format XML (generated by pytest, Jest, JUnit, etc.) into
a list of ExecutionResult objects keyed by TC ID.

TC ID extraction (priority order):
1. ``<property name="medharness.id" value="TC-SYS-001"/>`` — explicit
2. Regex match on test name: ``test_TC_SYS_001_*`` or ``TC-SYS-001_*``
3. No match → skipped silently

Links are extracted from ``<property name="medharness.links" value="SYS-001,CRS-002"/>``
if present; otherwise left empty (definition must be pre-registered).
"""

from __future__ import annotations

import re
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional

# Stable JUnit XML property namespace — downstream reporters should use these
JUNIT_ID = "medharness.id"
JUNIT_LINKS = "medharness.links"
JUNIT_TITLE = "medharness.title"
JUNIT_REVIEWER = "medharness.reviewer"
JUNIT_REVIEW_DATE = "medharness.review_date"
JUNIT_REVIEW_STATUS = "medharness.review_status"

# Matches: TC_SYS_001, TC-SYS-001, tc_sys_001, TC-CRS-009-001, TC-SRS-032-005
_TC_ID_RE = re.compile(
    r"(?:^|[^A-Za-z])(TC)[_-]([A-Z]+)[_-](\d+)(?:[_-](\d+))?",
    re.IGNORECASE,
)


@dataclass
class ExecutionResult:
    """A single test execution result parsed from JUnit XML."""

    id: str               # Normalised TC ID, e.g. TC-SYS-001
    testing_status: str   # PASS / FAIL / SKIP
    name: str             # Raw test name from XML
    links: List[str] = field(default_factory=list)  # from medharness.links property
    title: str = ""       # from medharness.title property (optional)
    reviewer: str = ""    # from medharness.reviewer property (optional)
    review_date: str = ""  # from medharness.review_date property (optional)
    review_status: str = ""  # from medharness.review_status property (optional)
    error_message: Optional[str] = None
    duration: float = 0.0


def parse_junit_xml(path: Path) -> List[ExecutionResult]:
    """Parse a JUnit XML file and return a list of ExecutionResult objects.

    Test cases with no recognisable TC ID are silently skipped.
    """
    tree = ET.parse(path)
    root = tree.getroot()

    results: List[ExecutionResult] = []
    for testcase in root.iter("testcase"):
        name = testcase.get("name", "")
        duration = float(testcase.get("time", 0) or 0)

        # Extract custom properties
        props = _parse_properties(testcase)
        tc_id = props.get(JUNIT_ID) or _extract_tc_id(name)
        if not tc_id:
            continue

        links_raw = props.get(JUNIT_LINKS, "")
        links = [lnk.strip() for lnk in links_raw.split(",") if lnk.strip()] if links_raw else []
        title = props.get(JUNIT_TITLE, "")
        reviewer = props.get(JUNIT_REVIEWER, "")
        review_date = props.get(JUNIT_REVIEW_DATE, "")
        review_status = props.get(JUNIT_REVIEW_STATUS, "")

        # Determine status
        if testcase.find("failure") is not None:
            status = "FAIL"
            failure_el = testcase.find("failure")
            error_message = failure_el.get("message") or (failure_el.text or "").strip()
        elif testcase.find("error") is not None:
            status = "FAIL"
            error_el = testcase.find("error")
            error_message = error_el.get("message") or (error_el.text or "").strip()
        elif testcase.find("skipped") is not None:
            status = "SKIP"
            error_message = None
        else:
            status = "PASS"
            error_message = None

        results.append(
            ExecutionResult(
                id=tc_id,
                testing_status=status,
                name=name,
                links=links,
                title=title,
                reviewer=reviewer,
                review_date=review_date,
                review_status=review_status,
                error_message=error_message,
                duration=duration,
            )
        )

    return results


def _parse_properties(testcase: ET.Element) -> dict:
    """Extract <property> elements inside a <testcase> into a dict."""
    props: dict = {}
    properties_el = testcase.find("properties")
    if properties_el is not None:
        for prop in properties_el.findall("property"):
            name = prop.get("name", "")
            value = prop.get("value", "")
            if name:
                props[name] = value
    return props


def _extract_tc_id(name: str) -> Optional[str]:
    """Extract a normalised TC ID from a test name string."""
    m = _TC_ID_RE.search(name)
    if not m:
        return None
    doc_type = m.group(2).upper()
    number = m.group(3).zfill(3)
    sub = m.group(4)
    if sub:
        return f"TC-{doc_type}-{number}-{sub.zfill(3)}"
    return f"TC-{doc_type}-{number}"
