#!/usr/bin/env python3
"""
Sync root AI-harness/ → compliantflow/data/product-template/AI-harness/

The root AI-harness/ is the single source of truth — CompliantFlow's own harness
for developing the tool. This script derives the product template from it for
delivery to users via `compliantflow init`.

Transformations applied to context.md:
  - Strip the ## Architecture section (CompliantFlow-specific internals)
  - Replace real values with {{placeholders}}
  - Add User-Configurable Settings footer

All other files (CLAUDE.md, AGENTS.md, GEMINI.md, checklists, adapters) are
copied as-is — they contain no CompliantFlow-specific values.

Run before building the package:
  python scripts/sync_product_template.py
"""
import re
import shutil
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
SRC = REPO_ROOT / "AI-harness"
DST = REPO_ROOT / "compliantflow" / "data" / "product-template" / "AI-harness"

GENERATED_HEADER = (
    "<!-- AUTO-GENERATED by scripts/sync_product_template.py — do not edit directly -->\n\n"
)

USER_CONFIGURABLE_FOOTER = """
---

## User-Configurable Settings

| Setting | Description |
|---------|-------------|
| `{{dhf_repo}}` | DHF repository — set during `compliantflow init` |
| Selected standards | `{{standards}}` — determines which policy checks run |
"""


def strip_architecture_section(text: str) -> str:
    """Remove the ## Architecture section and everything after it (it's the last section)."""
    pattern = r'\n---\n\n## Architecture\b.*$'
    return re.sub(pattern, '', text, flags=re.DOTALL)


def transform_context(text: str) -> str:
    text = strip_architecture_section(text)

    # Title + intro
    text = re.sub(
        r'^# CompliantFlow — Project Context\n\n.*?(?=\n---\n)',
        (
            '# Project Context — {{project_name}}\n\n'
            'This is the product repository for **{{project_name}}**, a medical device software '
            'project developed under **{{standards}}**.\n\n'
            'Compliance is enforced automatically on every PR via CompliantFlow. '
            'The Design History File (DHF) lives in a separate repository and tracks all '
            'regulatory documentation.'
        ),
        text,
        count=1,
        flags=re.DOTALL,
    )

    # Two-repo table rows
    text = text.replace(
        '| This repo (`CompliantFlow`) | CLI source code, tests, CI |',
        '| This repo | Product source code |',
    )
    text = text.replace(
        '| [`compliantflow-dhf`](https://github.com/itercharles/compliantflow-dhf)'
        ' | Design History File — requirements, risks, traceability, compliance records |',
        '| `{{dhf_repo}}` | Design History File — requirements, risks, traceability, compliance records |',
    )

    # Clone URL (Two-Repo Structure section)
    text = text.replace(
        'git clone https://github.com/itercharles/compliantflow-dhf\nexport PYTHONPATH=.:compliantflow-dhf/DHF',
        'git clone https://github.com/{{dhf_repo}} ../$(basename {{dhf_repo}})',
    )

    # DHF Commands: directory and header
    text = text.replace(
        "Run these from the DHF repo root (cloned alongside this repo at `compliantflow-dhf/`):",
        "Run these from the DHF repo root (cloned alongside this repo at `../$(basename {{dhf_repo}})`):",
    )
    text = text.replace('cd compliantflow-dhf\n', 'cd ../$(basename {{dhf_repo}})\n')

    # CR Workflow: create CR step
    text = text.replace(
        'cd compliantflow-dhf\nPYTHONPATH=.:DHF python -m utils item create --type CR',
        '# In the DHF repo\ncd ../$(basename {{dhf_repo}})\nPYTHONPATH=.:DHF python -m utils item create --type CR',
    )

    # Compliance Gate: CI workflow filename
    text = text.replace('`ci-pipeline.yml`', '`compliance.yml`')

    # Compliance Gate: policy check standards
    text = text.replace(
        'IEC 62304, ISO 14971 policy rules pass',
        '{{standards}} policy rules pass',
    )

    # Compliance Gate: local check paths
    text = text.replace(
        'DHF_DIR="compliantflow-dhf/DHF"\nGOVERNANCE_DIR="compliantflow-dhf/governance"',
        'DHF_DIR="../$(basename {{dhf_repo}})/DHF"\nGOVERNANCE_DIR="../$(basename {{dhf_repo}})/governance"',
    )

    # DHF Item Types: path reference
    text = text.replace(
        'All regulatory documentation lives in `compliantflow-dhf/DHF/items/`. Item types:',
        'All regulatory documentation lives in the DHF repo under `DHF/items/`. Item types:',
    )

    text += USER_CONFIGURABLE_FOOTER
    return GENERATED_HEADER + text


def sync() -> None:
    if DST.exists():
        shutil.rmtree(DST)

    shutil.copytree(
        SRC,
        DST,
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc", ".DS_Store"),
    )

    ctx = DST / "context.md"
    ctx.write_text(transform_context(ctx.read_text()))

    print(f"✓ Synced AI-harness/ → {DST.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    sync()
